wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1713431174.0
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      - 105
      2:
      - 1
      - 41
      - 51
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.9.0
      5: 0.16.6
      8:
      - 2
      - 5
      13: linux-x86_64
dataset_path:
  desc: null
  value: ../../paper_dataset
noisy_dataset_path:
  desc: null
  value: ../../paper_dataset
dataset:
  desc: null
  value: cifar100
noisy_dataset:
  desc: null
  value: cifar100
noise_mode:
  desc: null
  value: sym
noise_ratio:
  desc: null
  value: 0.9
open_ratio:
  desc: null
  value: 0.0
theta_s:
  desc: null
  value: 1.0
theta_r:
  desc: null
  value: 0.8
lambda_fc:
  desc: null
  value: 1.0
k:
  desc: null
  value: 200
model:
  desc: null
  value: PreResNet18
epochs:
  desc: null
  value: 300
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.02
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0005
seed:
  desc: null
  value: 3047
gpuid:
  desc: null
  value: '0'
entity:
  desc: null
  value: null
run_path:
  desc: null
  value: Dataset(cifar100_0.9_0.0_sym)_Model(0.8_1.0)
